### ISSUE TITLE
Fallback Values

### ISSUE THREAD

**Issue by LukeLarson2** [Chic-Fil-Async/Project-Atelier#82]
https://github.com/Chic-Fil-Async/Project-Atelier/blob/d2a52f49cce8533998fa225924e64ff99944f0d7/server/server.js#L11

MINOR ISSUE

Standard practice is to have your port given via environment variable with an alternate value as 3000 if no value is present in the environment, this way it allows for customization for anyone who clone your project.

`var port = process.env.PORT || 3000;`

**Comment by wtucker29** [comment]
Fixed in pull request #97
